# Generated by Django 4.2.26 on 2025-11-26 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('coins', models.IntegerField(default=100, verbose_name='游戏币')),
                ('level', models.IntegerField(default=1, verbose_name='等级')),
                ('experience', models.IntegerField(default=0, verbose_name='经验值')),
                ('bio', models.TextField(blank=True, verbose_name='个性签名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
    ]
