# Generated by Django 4.2.26 on 2025-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_checkin',
            field=models.DateField(blank=True, null=True, verbose_name='上次签到日期'),
        ),
    ]
