# Generated by Django 4.2.26 on 2025-11-27 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_knowledgenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='道具名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='道具图片')),
                ('effect_value', models.IntegerField(default=0, verbose_name='效果数值')),
            ],
            options={
                'verbose_name': '游戏道具',
                'verbose_name_plural': '游戏道具',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='web.gameitem', verbose_name='道具')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户背包',
                'verbose_name_plural': '用户背包',
                'ordering': ['-quantity', 'item__name'],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
