# Generated by Django 4.2.26 on 2025-11-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_gameitem_userinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameitem',
            options={'ordering': ['category', 'price'], 'verbose_name': '游戏道具', 'verbose_name_plural': '游戏道具'},
        ),
        migrations.AddField(
            model_name='gameitem',
            name='category',
            field=models.CharField(choices=[('equipment', '装备'), ('armor', '防具'), ('food', '食物'), ('item', '道具'), ('medicine', '药品')], default='item', max_length=20, verbose_name='分类'),
        ),
    ]
