# Generated by Django 4.2.26 on 2025-11-27 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_alter_gameitem_options_gameitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地块名称')),
                ('x_pos', models.IntegerField(help_text='0-100之间的整数', verbose_name='横坐标')),
                ('y_pos', models.IntegerField(help_text='0-100之间的整数', verbose_name='纵坐标')),
                ('price', models.IntegerField(verbose_name='系统初始售价')),
                ('building_type', models.CharField(choices=[('NONE', '空地'), ('APARTMENT', '胶囊公寓'), ('VILLA', '霓虹别墅'), ('TOWER', '摩天大楼')], default='NONE', max_length=20, verbose_name='建筑类型')),
                ('is_for_sale', models.BooleanField(default=False, verbose_name='是否正在转售')),
                ('resale_price', models.IntegerField(blank=True, null=True, verbose_name='转售价格')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_plots', to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
            options={
                'verbose_name': '地块',
                'verbose_name_plural': '地块',
                'ordering': ['name'],
            },
        ),
    ]
